<#
	.NOTES
	===========================================================================
	 Posted by : 	Powershell.com <yourpowertip@powershell.com>
	 Created on:   	09_22_2020 9:31 AM
	 Created by:   	CailleauThierry
	 Organization: 	Private
	 Filename: 		Get-WinEventExample.ps1
	===========================================================================
	.DESCRIPTION
	Version 7 and later
The Get-EventLog cmdlet provides easy access to event log entries in the primary Windows event logs, however it neither can access the many application level event logs, nor is it available at all in PowerShell 7.
If you ever plan to run your code in PowerShell 7, you should start getting used to its successor: Get-WinEvent. This cmdlet is powerful and supports many parameters. Here is an example that comes close to what Get-EventLog did:
Get-WinEvent -FilterHashtable @{Logname = 'System';Level= 2,3} -MaxEvents 10 |
  Select-Object TimeCreated, LevelDisplayName, Id , ProviderName, Message |
  Format-Table   
Your query is submitted in the form of a hash table, and you can see how to specify the log name and the number of events you want to get. In contrast to Get-EventLog, you can now specify and retrieve any log, not just the few classic logs. You may want to run Show-EventLog to open the event log viewer and discover the many available application level logs.
The hash table “Level” key defines the type of event log entry you want to see. The lower the number the more severe the entry. “2” represents errors, and “3” represents warnings. As you see, you can combine levels as comma-separated list.
The result looks similar to this:
TimeCreated         LevelDisplayName    Id ProviderName                     Message
-----------         ----------------    -- ------------                     -------
04.08.2020 13:03:42 Warning          10016 Microsoft-Windows-DistributedCOM The Anwendungsspezifisch permission settings do...
04.08.2020 13:03:20 Error                1 MTConfig                         An attempt to configure the input mode of a mul...
04.08.2020 13:03:19 Error                1 MTConfig                         An attempt to configure the input mode of a mul...
04.08.2020 12:58:18 Error                1 MTConfig                         An attempt to configure the input mode of a mul...
04.08.2020 11:53:38 Error            10010 Microsoft-Windows-DistributedCOM The server Microsoft.SkypeApp_15.61.100.0_x86__...
04.08.2020 11:23:48 Error            10010 Microsoft-Windows-DistributedCOM The server microsoft.windowscommunicationsapps_...
04.08.2020 11:23:41 Error            10010 Microsoft-Windows-DistributedCOM The server Microsoft.SkypeApp_15.61.100.0_x86__...
04.08.2020 11:23:37 Warning            701 Win32k                           Power Manager has not requested suppression of ...
04.08.2020 11:23:37 Warning            701 Win32k                           Power Manager has not requested suppression of ...
04.08.2020 11:23:37 Error            10317 Microsoft-Windows-NDIS           Miniport Microsoft Wi-Fi Direct Virtual Adapter... 

#>

Get-WinEvent -FilterHashtable @{Logname = 'System';Level= 2,3} -MaxEvents 10 | Select-Object TimeCreated,LevelDisplayName,Id,ProviderName,Message | Format-Table

# Tested to also work on PSVersion  5.1.19041.1

<#
PS C:\Users\username\Documents\WindowsPowerShell\Scripts\PowerShellDotCom> c:\Users\username\Documents\WindowsPowerShell\Scripts\PowerShellDotCom\Get-WinEventExample.ps1

TimeCreated           LevelDisplayName    Id ProviderName                        Message
-----------           ----------------    -- ------------                        -------
9/22/2020 11:55:00 AM Warning           8015 Microsoft-Windows-DNS-Client        The system failed to register host (A or AAAA) resource records (RRs) for network adapter...
9/22/2020 11:54:25 AM Warning           1014 Microsoft-Windows-DNS-Client        Name resolution for the name opentext.net timed out after none of the configured DNS servers responded.
9/22/2020 11:53:41 AM Warning           8015 Microsoft-Windows-DNS-Client        The system failed to register host (A or AAAA) resource records (RRs) for network adapter...
9/22/2020 11:50:47 AM Warning          10016 Microsoft-Windows-DistributedCOM    The application-specific permission settings do not grant Local Activation permission for the COM Server applicati... 
9/22/2020 11:45:04 AM Warning           1112 Microsoft-Windows-GroupPolicy       The Group Policy Client Side Extension Software Installation was unable to apply one or more settings because the ... 
9/22/2020 11:45:04 AM Warning            108 Application Management Group Policy Failed to apply changes to software installation settings.  The installation of software deployed through Group Po...
9/22/2020 11:45:04 AM Error              103 Application Management Group Policy The removal of the assignment of application ConfigMgr Client Setup Bootstrap from policy SCCM_Deploy_Agent_1910 f... 
9/22/2020 11:45:04 AM Warning            101 Application Management Group Policy The assignment of application ConfigMgr Client Setup Bootstrap from policy SCCM_Deploy_Agent_1910 failed.  The err... 
9/22/2020 11:23:41 AM Warning           8015 Microsoft-Windows-DNS-Client        The system failed to register host (A or AAAA) resource records (RRs) for network adapter...
9/22/2020 10:55:00 AM Warning           8015 Microsoft-Windows-DNS-Client        The system failed to register host (A or AAAA) resource records (RRs) for network adapter...
#>

